# Generated by Django 6.0.4 on 2026-04-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
